### ISSUE TITLE
ConPlot doesn't accept a PDB file with a sequence different than the query

### ISSUE THREAD

**Issue by sadiogo** [rigdenlab/conkit-web#139]
**Describe the bug**
I tried plotting a situation akin to the following example:
```
>sequence
MAVFYD
```
PDB:
```
 1   2   3  4   5   6 
ILE SER THR TYR TRP GLU
```
Which is equivalent to saying:
```
SEQ: MAVFYD
PDB: ISTYWE
```
And I get the following message, which is displayed in a modal:
```
We were unable to match the sequence at seq.fasta with the data at the file 4e7n_mod.pdb. Please ensure that the file you attempt to upload corresponds with the protein sequence in the provided FASTA file.
```

**Expected behavior**
I would expect that since the PDB structure has the exact number of residues as the query, it would plot both contact maps regardless if their sequence were identical.

**Desktop (please complete the following information):**
 - Windows 11
 - Brave Browser
 - Version 1.34.80```

**Additional context**
I've talked about this in the conkit project. When trying to plot this using conkit, I get the following error:
```
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sadiogo/.local/lib/python3.6/site-packages/conkit/command_line/conkit_plot.py", line 441, in <module>
    main()
  File "/home/sadiogo/.local/lib/python3.6/site-packages/conkit/command_line/conkit_plot.py", line 303, in main
    reference = conkit.io.read(args.reffile, args.refformat)[0]
  File "/home/sadiogo/.local/lib/python3.6/site-packages/conkit/io/__init__.py", line 131, in read
    hierarchy = parser_in.read(f_in, **kwargs)
  File "/home/sadiogo/.local/lib/python3.6/site-packages/conkit/io/pdb.py", line 288, in read
    return self._read(structure, f_id, distance_cutoff, atom_type)
  File "/home/sadiogo/.local/lib/python3.6/site-packages/conkit/io/pdb.py", line 172, in _read
    contact_map.add(contact)
  File "/home/sadiogo/.local/lib/python3.6/site-packages/conkit/core/entity.py", line 218, in add
    raise ValueError("%s defined twice" % str(entity.id))
ValueError: (35, 38) defined twice
```

**Comment by FilomenoSanchez** [comment]
Would it be possible to attach the input files or do they contain sensible data? It would make figuring out what's going on a bit easier.

**Comment by sadiogo** [comment]
Sure

[test_dataset.zip](https://github.com/rigdenlab/conplot/files/7905921/test_dataset.zip)

**Comment by FilomenoSanchez** [comment]
Thanks for the files. I've noticed that the residues in the sequence do not correspond with the numbering in the PDB file. The FASTA sequence is:
```
>TEST_SEQUENCE
IIGGDMARTINSDESAALYKSGRFRCGGTLINQEWVLTAAHCDRRNMEIKLGMHSKNVPNEDEQRRVPKEKFFCDSNKNYTQWNKDIMLIRLNSPVNNST
HIAPLSLPSSPPIVGSVCRIMGWGTITSPNETYPDVPHCANINLFNYTVCHGAHAGLPATSRTLCAGVLEGGKDTCKGDSGGPLICNGQFQGIVSWGGHP
CAQPREPGVYTKVFDHLDWIQNIIAGS
```
While the residue numbers in the PDB file are as follows (they seem to have an offset of 15 residues):
```
 ILE 16
 ILE 17
 GLY 18
 GLY 19
 ASP 20
 [...]
```
For this to work, the residue numbers in the PDB file should be:
```
 ILE 1
 ILE 2
 GLY 3
 GLY 4
 ASP 5
 [...]
```
You will need to renumber the residues in the PDB file. I will answer the conkit question in the other issue.

**Comment by sadiogo** [comment]
Yup, that PDB file was a complete mess. I had already corrected loads of stuff, but there were still 6 residues with duplicated numbering. I fixed it and everything worked fine in ConPlot. But not in Conkit.

**Comment by FilomenoSanchez** [comment]
Closing this now since the problem seems fixed in ConPlot.
